[install]
az.pkg-path = "azure-cli"
az-functions.pkg-path = "azure-functions-core-tools-8"
terraform.pkg-path = "terraform"
terragrunt.pkg-path = "terragrunt"
kubectl.pkg-path = "kubernetes"
helm.pkg-path = "helm"
k9s.pkg-path = "k9s"

[vars]
AZURE_TF_RESOURCE_GROUP = "flox"
AZURE_TF_LOCATION = "eastus"

[profile.common]
alias tf="terraform"
alias tg="terragrunt"
alias k="kubectl"
alias k9s="k9s --context k8s-aks"
