[install]
gh.pkg-path = "gh"
act.pkg-path = "act"
lazygit.pkg-path = "lazygit"
delta.pkg-path = "delta"
git.pkg-path = "git"
git-lfs.pkg-path = "git-lfs"

[profile.bash]
alias gg="lazygit"
alias gd="git diff | delta"
alias gs="git status"

[profile.zsh]
gg() { lazygit $@; }
gd() { git diff | delta $@; }
gs() { git status $@; }
